### ISSUE TITLE
Add a Kafka connector section

### ISSUE THREAD

**Issue by OlivierAlbertini** [zeebe-io/zeebe-docker-compose#10]
Hi,

I'm new with Kafka and I tried to link Kafka / Kafka connector / Zeebe borker without success. I'm not very familiar this kind of configuration.

Would it be possible to add an example with a basic configuration ? In this way we could play around that ?

Thanks a lot.

**Comment by npepinpe** [comment]
Hey Olivier,

the [kafka-connect-zeebe](https://github.com/zeebe-io/kafka-connect-zeebe) contains a [docker-compose.yml](https://github.com/zeebe-io/kafka-connect-zeebe/blob/master/docker/docker-compose.yml) which sets up Zeebe, Kafka, and Connect, as well as [example configurations](https://github.com/zeebe-io/kafka-connect-zeebe/tree/master/examples) and [quickstart properties](https://github.com/zeebe-io/kafka-connect-zeebe/tree/master/config). The main repo explains how to configure the connector in more detail, both [sink](https://github.com/zeebe-io/kafka-connect-zeebe#sink-connector) and [source](https://github.com/zeebe-io/kafka-connect-zeebe#source).

I'm glad to hear if you have any feedback if things aren't clear, the connector project is still very much a work in progress. I'm at home right now but I can post a simpler docker example tomorrow morning if this isn't clear.

**Comment by OlivierAlbertini** [comment]
@npepinpe Thanks you so much!
