### ISSUE TITLE
exporter demo old verion

### ISSUE THREAD

**Issue by Gorynych** [zeebe-io/zeebe-docker-compose#22]
There's an old build of zeebe-exporter-demo-1.0-SNAPSHOT.jar 
It causes the "NoClassDefFoundError: io/zeebe/exporter/api/spi/Exporter" exeption.

**Comment by jwulf** [comment]
I've updated the source for that exporter here: https://github.com/jwulf/zeebe-exporter-demo

And I'm removing it from this repo, to reduce the amount of maintenance updates required.
