### ISSUE TITLE
Cluster example includes deprecated environment variables

### ISSUE THREAD

**Issue by daghb** [zeebe-io/zeebe-docker-compose#31]
Should at least rename

ZEEBE_NODE_ID -> ZEEBE_BROKER_CLUSTER_NODEID
ZEEBE_CONTACT_POINTS -> ZEEBE_BROKER_CLUSTER_INITIALCONTACTPOINTS

There may be more of these.

**Comment by auduongtansang** [comment]
ZEEBE_PARTITIONS_COUNT ===> ZEEBE_BROKER_CLUSTER_PARTITIONSCOUNT
ZEEBE_REPLICATION_FACTOR ===> ZEEBE_BROKER_CLUSTER_REPLICATIONFACTOR
ZEEBE_CLUSTER_SIZE ===> ZEEBE_BROKER_CLUSTER_CLUSTERSIZE

**Comment by jwulf** [comment]
Updated. Thanks!

**Comment by roshan8** [comment]
@jwulf `ZEEBE_GATEWAY_CLUSTER_CONTACTPOINT` can only take one host as a parameter right?
standalone-gateway/docker-compose.yml mentions 3 hosts for this parameter.
