### ISSUE TITLE
zbctl 0.26.0 not compatible with Zeebe 1.0.0

### ISSUE THREAD

**Issue by mmiklus** [zeebe-io/zeebe-docker-compose#39]
"deploy" RPC is not compatible between zbctl 0.26.0 (from zeebe-docker-compose/bin/)
and Zeebe 1.0.0 broker (deployed via "cd ./operate/ ; docker-compose up -d")

$ ./zbctl --insecure deploy ../bpmn/diagram_1.bpmn
Error: rpc error: code = Unimplemented desc = Method not found: gateway_protocol.Gateway/DeployWorkflow

$ ./zbctl --insecure status
Cluster size: 1
Partitions count: 1
Replication factor: 1
Gateway version: 1.0.0
Brokers:
  Broker 0 - 172.18.0.3:26501
    Version: 1.0.0
    Partition 1 : Leader, Healthy

**Comment by mmiklus** [comment]
Fixed in PR - #40 
updated README and binaries from release: https://github.com/camunda-cloud/zeebe/releases

**Comment by jwulf** [comment]
Merged PR. Thanks!
