### ISSUE TITLE
Upgrade to Camunda Cloud 1.2

### ISSUE THREAD

**Issue by lenaschoenburg** [zeebe-io/zeebe-docker-compose#50]
It'd be great to upgrade to Camunda Cloud 1.2. We sometimes get bug reports for Zeebe 1.1.0 because users try to use the docker-compose files here and at least for me it's sometimes difficult to figure out if they are issues fixed in later releases. 
I believe there will be a few configs that'll need to be adjusted so it's not as easy as telling users to simply replace the `1.1.0` tags with `1.2.2`.

**Comment by jwulf** [comment]
It sounds like people use them. I do. 

Pull requests to update to latest configs - especially when there are changes between versions - would be good.

**Comment by berndruecker** [comment]
@Hafflgav thought about providing a PR - but we also wanted to wait for the discussion in https://github.com/camunda-community-hub/zeebe-docker-compose/issues/52

**Comment by berndruecker** [comment]
We will retire this repo - so no action required any more
